language: node_js
node_js: 
  - "stable"
env:
  - NODE_ENV=test
branches:
  only:
  - main
  - develop
before_install:
  - curl -sL https://firebase.tools | bash
cache:
  directories:
    - "node_modules"
script: npm test